# Generated by Django 4.0.3 on 2022-03-09 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα σχολικής μονάδας')),
                ('code', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='Ο κωδικός ΥΠΑΙΘ πρέπει να είναι αριθμός με 7 ψηφία.', regex='^\\d{7}$')], verbose_name='Κωδικός ΥΠΑΙΘ')),
                ('type', models.CharField(max_length=40, verbose_name='Τύπος')),
                ('email1', models.CharField(max_length=50, verbose_name='E-mail')),
                ('dimos', models.CharField(max_length=50, verbose_name='Δήμος')),
                ('tel', models.CharField(max_length=40, verbose_name='Τηλέφωνο')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sch_head1', models.CharField(max_length=100, verbose_name='Ον/μο Δ/ντή/-ντριας')),
                ('name1', models.CharField(max_length=100, verbose_name='Όνοματεπώνυμο Συντονιστή/τριας')),
                ('email1', models.EmailField(max_length=254, verbose_name='email Συντονιστή/τριας')),
                ('mobile1', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Ο αρ. τηλεφώνου πρέπει να είναι αριθμός με 10 ψηφία.', regex='^\\d{10}$')], verbose_name='Κινητό τηλέφωνο Συντονιστή/τριας')),
                ('eidikothta1', models.CharField(choices=[('ΠΕ60', 'ΠΕ60 Νηπιαγωγών'), ('ΠΕ70', 'ΠΕ70 Δασκάλων'), ('ΠΕ05', 'ΠΕ05 Γαλλικών'), ('ΠΕ06', 'ΠΕ06 Αγγλικών'), ('ΠΕ07', 'ΠΕ07 Γερμανικών'), ('ΠΕ08', 'ΠΕ08 Καλλιτεχνικών'), ('ΠΕ11', 'ΠΕ11 Φυσικής αγωγής'), ('ΠΕ79', 'ΠΕ79 Μουσικών'), ('ΠΕ23', 'Ψυχολόγων'), ('ΠΕ26', 'Λογοθεραπευτών'), ('ΠΕ28', 'Φυσικοθεραπευτών'), ('ΠΕ86', 'Πληροφορικής'), ('ΠΕ30', 'Κοιν.Λειτουργών'), ('ΔΕ1ΕΒΠ', 'Βοηθ.Προσ.Ειδ.Αγ.'), ('ΠΕ60ΕΑΕ', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ61', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ70ΕΑΕ', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ71', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ91', 'Θεατρικών Σπουδών'), ('ΠΕ25', 'Σχ.Νοσηλευτών'), ('ΠΕ21', 'Λογοθεραπευτών'), ('ΠΕ29', 'Εργοθεραπευτών'), ('ΤΕ16', 'Μουσικών Τ.Ε.')], max_length=40, verbose_name='Ειδικότητα Συντονιστή/τριας')),
                ('history1', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Υλοποίηση προγραμμάτων Συντονιστή/τριας στο παρελθόν')),
                ('qual1', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Επιμόρφωση Συντονιστή/τριας')),
                ('name2', models.CharField(max_length=100, verbose_name='Όνοματεπώνυμο 2ου εκπ/κού')),
                ('email2', models.EmailField(max_length=254, verbose_name='email 2ου εκπ/κού')),
                ('mobile2', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Ο αρ. τηλεφώνου πρέπει να είναι αριθμός με 10 ψηφία.', regex='^\\d{10}$')], verbose_name='Κινητό τηλέφωνο 2ου εκπ/κού')),
                ('eidikothta2', models.CharField(choices=[('ΠΕ60', 'ΠΕ60 Νηπιαγωγών'), ('ΠΕ70', 'ΠΕ70 Δασκάλων'), ('ΠΕ05', 'ΠΕ05 Γαλλικών'), ('ΠΕ06', 'ΠΕ06 Αγγλικών'), ('ΠΕ07', 'ΠΕ07 Γερμανικών'), ('ΠΕ08', 'ΠΕ08 Καλλιτεχνικών'), ('ΠΕ11', 'ΠΕ11 Φυσικής αγωγής'), ('ΠΕ79', 'ΠΕ79 Μουσικών'), ('ΠΕ23', 'Ψυχολόγων'), ('ΠΕ26', 'Λογοθεραπευτών'), ('ΠΕ28', 'Φυσικοθεραπευτών'), ('ΠΕ86', 'Πληροφορικής'), ('ΠΕ30', 'Κοιν.Λειτουργών'), ('ΔΕ1ΕΒΠ', 'Βοηθ.Προσ.Ειδ.Αγ.'), ('ΠΕ60ΕΑΕ', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ61', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ70ΕΑΕ', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ71', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ91', 'Θεατρικών Σπουδών'), ('ΠΕ25', 'Σχ.Νοσηλευτών'), ('ΠΕ21', 'Λογοθεραπευτών'), ('ΠΕ29', 'Εργοθεραπευτών'), ('ΤΕ16', 'Μουσικών Τ.Ε.')], max_length=40, verbose_name='Ειδικότητα 2ου εκπ/κού')),
                ('history2', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Υλοποίηση προγραμμάτων 2ου εκπ/κού στο παρελθόν')),
                ('qual2', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Επιμόρφωση 2ου εκπ/κού')),
                ('name3', models.CharField(max_length=100, verbose_name='Όνοματεπώνυμο 3ου εκπ/κού')),
                ('email3', models.EmailField(max_length=254, verbose_name='email 3ου εκπ/κού')),
                ('mobile3', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Ο αρ. τηλεφώνου πρέπει να είναι αριθμός με 10 ψηφία.', regex='^\\d{10}$')], verbose_name='Κινητό τηλέφωνο 3ου εκπ/κού')),
                ('eidikothta3', models.CharField(choices=[('ΠΕ60', 'ΠΕ60 Νηπιαγωγών'), ('ΠΕ70', 'ΠΕ70 Δασκάλων'), ('ΠΕ05', 'ΠΕ05 Γαλλικών'), ('ΠΕ06', 'ΠΕ06 Αγγλικών'), ('ΠΕ07', 'ΠΕ07 Γερμανικών'), ('ΠΕ08', 'ΠΕ08 Καλλιτεχνικών'), ('ΠΕ11', 'ΠΕ11 Φυσικής αγωγής'), ('ΠΕ79', 'ΠΕ79 Μουσικών'), ('ΠΕ23', 'Ψυχολόγων'), ('ΠΕ26', 'Λογοθεραπευτών'), ('ΠΕ28', 'Φυσικοθεραπευτών'), ('ΠΕ86', 'Πληροφορικής'), ('ΠΕ30', 'Κοιν.Λειτουργών'), ('ΔΕ1ΕΒΠ', 'Βοηθ.Προσ.Ειδ.Αγ.'), ('ΠΕ60ΕΑΕ', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ61', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ70ΕΑΕ', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ71', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ91', 'Θεατρικών Σπουδών'), ('ΠΕ25', 'Σχ.Νοσηλευτών'), ('ΠΕ21', 'Λογοθεραπευτών'), ('ΠΕ29', 'Εργοθεραπευτών'), ('ΤΕ16', 'Μουσικών Τ.Ε.')], max_length=40, verbose_name='Ειδικότητα 3ου εκπ/κού')),
                ('history3', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Υλοποίηση προγραμμάτων 3ου εκπ/κού στο παρελθόν')),
                ('qual3', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Επιμόρφωση 3ου εκπ/κού')),
                ('title', models.TextField(verbose_name='Τίτλος προγράμματος')),
                ('category', models.CharField(choices=[('Αγωγής Υγείας', 'Αγωγής Υγείας'), ('Περιβαλλοντικής Εκπαίδευσης', 'Περιβαλλοντικής Εκπαίδευσης'), ('Πολιτιστικών Θεμάτων', 'Πολιτιστικών Θεμάτων')], max_length=27, verbose_name='Κατηγορία προγράμματος')),
                ('praxi', models.IntegerField(verbose_name='Πράξη ανάθεσης')),
                ('praxidate', models.DateField(verbose_name='Ημ/νία πράξης')),
                ('tmimata', models.TextField(verbose_name='Τμήμα/τμήματα')),
                ('students_nr', models.IntegerField(verbose_name='Αριθμός Μαθητών')),
                ('students_nr_boys', models.IntegerField(verbose_name='Αριθμός αγοριών')),
                ('students_nr_girls', models.IntegerField(verbose_name='Αριθμός κοριτσιών')),
                ('chars', models.CharField(choices=[('Μικτή ομάδα', 'Μικτή ομάδα'), ('Αμιγές τμήμα', 'Αμιγές τμήμα')], max_length=12, verbose_name='Χαρακτηριστικά ομάδας')),
                ('arxeio', models.CharField(max_length=3, verbose_name='Ύπαρξη αρχείου Σχολικών Δραστηριοτήτων στο Σχολείο')),
                ('theme', models.TextField(verbose_name='Κύριο θέμα - Θεματικές Ενότητες')),
                ('goal', models.TextField(verbose_name='Παιδαγωγικοί στόχοι')),
                ('methodology', models.TextField(verbose_name='Μεθοδολογία Υλοποίησης')),
                ('duration', models.CharField(choices=[('2 μήνες', '2 μήνες'), ('3 μήνες', '3 μήνες'), ('4 μήνες', '4 μήνες'), ('5 μήνες', '5 μήνες')], max_length=7, verbose_name='Προβλεπόμενη διάρκεια προγράμματος (μήνες)')),
                ('month', models.CharField(max_length=20, verbose_name='Μήνας έναρξης')),
                ('visits', models.TextField(verbose_name='Αριθμός προβλεπόμενων επισκέψεων - Συνεργασίες με άλλους φορείς')),
                ('foreis', models.TextField(verbose_name='Φορείς επισκέψεων')),
                ('pedia', models.TextField(verbose_name='Πεδία σύνδεσης με τα προγράμματα σπουδών των αντίστοιχων γνωστικών αντικειμένων')),
                ('diaxysh', models.CharField(choices=[('Έντυπη έκδοση', 'Έντυπη έκδοση'), ('Αναρτήσεις στο διαδίκτυο', 'Αναρτήσεις στο διαδίκτυο'), ('Παραγωγή βίντεο', 'Παραγωγή βίντεο'), ('Αφίσες - φυλλάδια', 'Αφίσες - φυλλάδια'), ('Έκθεση κατασκευών - χειροτεχνιών - φωτογραφιών', 'Έκθεση κατασκευών - χειροτεχνιών - φωτογραφιών'), ('Παρεμβάσεις', 'Παρεμβάσεις'), ('Άλλο', 'Άλλο')], max_length=136, verbose_name='Τρόποι διάχυσης')),
                ('diaxysh_other', models.TextField(verbose_name='Άλλοι τρόποι διάχυσης')),
                ('mon1', models.TextField(verbose_name='1ος Μήνας')),
                ('mon2', models.TextField(verbose_name='2ος Μήνας')),
                ('mon3', models.TextField(verbose_name='3ος Μήνας')),
                ('mon4', models.TextField(verbose_name='4ος Μήνας')),
                ('mon5', models.TextField(verbose_name='5ος Μήνας')),
                ('prsnt', models.CharField(choices=[('Ναι', 'Ναι'), ('Ίσως', 'Ίσως'), ('Όχι', 'Όχι')], max_length=4)),
                ('notes', models.TextField(verbose_name='Τυχόν παρατηρήσεις-επισημάνσεις')),
                ('checked', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Βεβαιώνεται ότι ο/η δ/ντής/τρια ή προϊσταμένος/νη της σχολικής μονάδας έλεγξε το παρόν σχέδιο προγράμματος σχολικών δραστηριοτήτων, έκανε απαραίτητες τυχόν διορθώσεις και βεβαιώνει ότι τα στοιχεία που αναφέρονται στο παρόν σχέδιο προγράμματος είναι σωστά.')),
                ('vev', models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Ο/Η  δ/ντής/τρια ή προϊσταμένος/νη βεβαιώνει ότι το συγκεκριμένο σχέδιο προγράμματος σχολικών δραστηριοτήτων ολοκληρώθηκε επιτυχώς και τα αποτελέσματα του προγράμματος είναι διαθέσιμα στο σχολική μονάδα.')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('school1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sch_progs.school', verbose_name='Σχολείο')),
            ],
        ),
    ]
