# Generated by Django 4.0.3 on 2022-03-09 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sch_progs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='arxeio',
            field=models.CharField(choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Ύπαρξη αρχείου Σχολικών Δραστηριοτήτων στο Σχολείο'),
        ),
        migrations.AlterField(
            model_name='program',
            name='diaxysh',
            field=models.CharField(blank=True, choices=[('Έντυπη έκδοση', 'Έντυπη έκδοση'), ('Αναρτήσεις στο διαδίκτυο', 'Αναρτήσεις στο διαδίκτυο'), ('Παραγωγή βίντεο', 'Παραγωγή βίντεο'), ('Αφίσες - φυλλάδια', 'Αφίσες - φυλλάδια'), ('Έκθεση κατασκευών - χειροτεχνιών - φωτογραφιών', 'Έκθεση κατασκευών - χειροτεχνιών - φωτογραφιών'), ('Παρεμβάσεις', 'Παρεμβάσεις'), ('Άλλο', 'Άλλο')], max_length=136, verbose_name='Τρόποι διάχυσης'),
        ),
        migrations.AlterField(
            model_name='program',
            name='diaxysh_other',
            field=models.TextField(blank=True, verbose_name='Άλλοι τρόποι διάχυσης'),
        ),
        migrations.AlterField(
            model_name='program',
            name='eidikothta3',
            field=models.CharField(blank=True, choices=[('ΠΕ60', 'ΠΕ60 Νηπιαγωγών'), ('ΠΕ70', 'ΠΕ70 Δασκάλων'), ('ΠΕ05', 'ΠΕ05 Γαλλικών'), ('ΠΕ06', 'ΠΕ06 Αγγλικών'), ('ΠΕ07', 'ΠΕ07 Γερμανικών'), ('ΠΕ08', 'ΠΕ08 Καλλιτεχνικών'), ('ΠΕ11', 'ΠΕ11 Φυσικής αγωγής'), ('ΠΕ79', 'ΠΕ79 Μουσικών'), ('ΠΕ23', 'Ψυχολόγων'), ('ΠΕ26', 'Λογοθεραπευτών'), ('ΠΕ28', 'Φυσικοθεραπευτών'), ('ΠΕ86', 'Πληροφορικής'), ('ΠΕ30', 'Κοιν.Λειτουργών'), ('ΔΕ1ΕΒΠ', 'Βοηθ.Προσ.Ειδ.Αγ.'), ('ΠΕ60ΕΑΕ', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ61', 'Νηπιαγωγών Ειδ.Αγ.'), ('ΠΕ70ΕΑΕ', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ71', 'Δασκάλων Ειδ.Αγωγ.'), ('ΠΕ91', 'Θεατρικών Σπουδών'), ('ΠΕ25', 'Σχ.Νοσηλευτών'), ('ΠΕ21', 'Λογοθεραπευτών'), ('ΠΕ29', 'Εργοθεραπευτών'), ('ΤΕ16', 'Μουσικών Τ.Ε.')], max_length=40, verbose_name='Ειδικότητα 3ου εκπ/κού'),
        ),
        migrations.AlterField(
            model_name='program',
            name='email1',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email Συντονιστή/τριας'),
        ),
        migrations.AlterField(
            model_name='program',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email 2ου εκπ/κού'),
        ),
        migrations.AlterField(
            model_name='program',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email 3ου εκπ/κού'),
        ),
        migrations.AlterField(
            model_name='program',
            name='foreis',
            field=models.TextField(blank=True, verbose_name='Φορείς επισκέψεων'),
        ),
        migrations.AlterField(
            model_name='program',
            name='history1',
            field=models.CharField(blank=True, choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Υλοποίηση προγραμμάτων Συντονιστή/τριας στο παρελθόν'),
        ),
        migrations.AlterField(
            model_name='program',
            name='history2',
            field=models.CharField(blank=True, choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Υλοποίηση προγραμμάτων 2ου εκπ/κού στο παρελθόν'),
        ),
        migrations.AlterField(
            model_name='program',
            name='history3',
            field=models.CharField(blank=True, choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Υλοποίηση προγραμμάτων 3ου εκπ/κού στο παρελθόν'),
        ),
        migrations.AlterField(
            model_name='program',
            name='mon1',
            field=models.TextField(blank=True, verbose_name='1ος Μήνας'),
        ),
        migrations.AlterField(
            model_name='program',
            name='mon2',
            field=models.TextField(blank=True, verbose_name='2ος Μήνας'),
        ),
        migrations.AlterField(
            model_name='program',
            name='mon3',
            field=models.TextField(blank=True, verbose_name='3ος Μήνας'),
        ),
        migrations.AlterField(
            model_name='program',
            name='mon4',
            field=models.TextField(blank=True, verbose_name='4ος Μήνας'),
        ),
        migrations.AlterField(
            model_name='program',
            name='mon5',
            field=models.TextField(blank=True, verbose_name='5ος Μήνας'),
        ),
        migrations.AlterField(
            model_name='program',
            name='month',
            field=models.CharField(blank=True, max_length=20, verbose_name='Μήνας έναρξης'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name3',
            field=models.CharField(blank=True, max_length=100, verbose_name='Όνοματεπώνυμο 3ου εκπ/κού'),
        ),
        migrations.AlterField(
            model_name='program',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Τυχόν παρατηρήσεις-επισημάνσεις'),
        ),
        migrations.AlterField(
            model_name='program',
            name='pedia',
            field=models.TextField(blank=True, verbose_name='Πεδία σύνδεσης με τα προγράμματα σπουδών των αντίστοιχων γνωστικών αντικειμένων'),
        ),
        migrations.AlterField(
            model_name='program',
            name='prsnt',
            field=models.CharField(choices=[('Ναι', 'Ναι'), ('Ίσως', 'Ίσως'), ('Όχι', 'Όχι')], max_length=4, verbose_name='Πρόθεση παρουσίασης προγράμματος σε εκδήλωση'),
        ),
        migrations.AlterField(
            model_name='program',
            name='qual1',
            field=models.CharField(blank=True, choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Επιμόρφωση Συντονιστή/τριας'),
        ),
        migrations.AlterField(
            model_name='program',
            name='qual2',
            field=models.CharField(blank=True, choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Επιμόρφωση 2ου εκπ/κού'),
        ),
        migrations.AlterField(
            model_name='program',
            name='qual3',
            field=models.CharField(blank=True, choices=[('Ναι', 'Ναι'), ('Όχι', 'Όχι')], max_length=3, verbose_name='Επιμόρφωση 3ου εκπ/κού'),
        ),
        migrations.AlterField(
            model_name='program',
            name='students_nr_boys',
            field=models.IntegerField(blank=True, verbose_name='Αριθμός αγοριών'),
        ),
        migrations.AlterField(
            model_name='program',
            name='students_nr_girls',
            field=models.IntegerField(blank=True, verbose_name='Αριθμός κοριτσιών'),
        ),
        migrations.AlterField(
            model_name='program',
            name='visits',
            field=models.TextField(blank=True, verbose_name='Αριθμός προβλεπόμενων επισκέψεων - Συνεργασίες με άλλους φορείς'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email1',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='school',
            name='type',
            field=models.CharField(choices=[('Δημοτικό', 'Δημοτικό σχολείο'), ('Νηπιαγωγείο', 'Νηπιαγωγείο')], max_length=20, verbose_name='Τύπος'),
        ),
    ]
